### ISSUE TITLE
Missing libGLEW.so.2.0 in AppImage

### ISSUE THREAD

**Issue by probonopd** [RicardoEPRodrigues/3Engine#4]
When running on Ubuntu 14.04. getting

![](https://github.com/AppImage/appimage.github.io/blob/4180b8f9ff5a2408656199a2ba6ebe620e38d63b/database/3Engine/screenshot.png?raw=true)

How did you generate the AppImage? Please ensure that all dependency libraries except [those](https://github.com/AppImage/AppImages/blob/master/excludelist) are bundled.

Thanks.

Reference:
https://github.com/AppImage/appimage.github.io/pull/675

**Comment by RicardoEPRodrigues** [comment]
It appears GLEW and FreeGLUT depend on drivers from the OS, since I'm running on NVIDIA it ties itself with it. Meaning that I need to build for NVIDIA/MESA/... etc. Otherwise I can't include the libraries...

I want to change to SDL and I hope that with it these problems disappear.

For now you still need to install the needed dependencies. `sudo apt install freeglut3-dev libglew-dev`

**Comment by probonopd** [comment]
OK, thanks for the clarification. What would happen if you simply would bundle the missing library?

**Comment by RicardoEPRodrigues** [comment]
Lets say I bundle the libraries in a system with NVIDIA.

If the other system uses NVIDIA, then it runs. Otherwise it fails.

From what I researched SDL doesn't requires specific drivers, meaning that in the future I may be able to bundle a fully working SDL OpenGL application.

**Comment by probonopd** [comment]
Looks like we should add those libraries to our global excludelist then. Can you say which libraries exactly are like this?

**Comment by RicardoEPRodrigues** [comment]
My builds use `libGLEW.so.2.0` and `libglut.so.3`.

Hope it helps.

**Comment by probonopd** [comment]
Thank you!

**Comment by RicardoEPRodrigues** [comment]
I booted a Ubuntu 14.04 and tried to install the missing dependencies.

It appears that GLEW 2.0 is not available on 14.04, in those repos the available version is 1.2 I believe. That is another issue.

**Comment by probonopd** [comment]
This means that this application cannot run on the oldest still-supported LTS release then.

**Comment by RicardoEPRodrigues** [comment]
Yes. I'll have to write some restriction on the Hardware and Software.

Although not a really complex program, I want to work on the most recent platforms.

**Comment by darealshinji** [comment]
I stumbled upon this comment from https://github.com/AppImage/pkg2appimage/blob/master/excludelist

> \# The following may be spefific to a particular GPU and may need to be excluded
> \# according to https://github.com/RicardoEPRodrigues/3Engine/issues/4#issuecomment-402532194
> \# libGLEW.so.2.0 # to be confirmed

libGLEW is not tied to a specific GPU. It's linked against `libGL.so.1` and that one is different depending on the installed driver. In fact libGLEW is [changing its soversion very often](https://packages.ubuntu.com/search?keywords=libglew), so you should always include it.

**Comment by RicardoEPRodrigues** [comment]
@darealshinji Hello, thank you for your input.

You are completely right. I was actually importing the wrong `.so` files a while back. Since then I updated the libraries needed to generate the AppImage.

For a little more clarity I leave here the libraries I import to my AppImage (and are therefore not dependent on the system):

```
/usr/lib/x86_64-linux-gnu/libOpenGL.so*
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so*
/usr/lib/x86_64-linux-gnu/libSDL2.so
/usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so*
/usr/lib/x86_64-linux-gnu/libSDL2_image.so
/usr/lib/x86_64-linux-gnu/libSDL2_mixer-2.0.so*
/usr/lib/x86_64-linux-gnu/libSDL2_mixer.so
/usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so*
/usr/lib/x86_64-linux-gnu/libSDL2_ttf.so
/usr/lib/x86_64-linux-gnu/libGLEW.so*
/usr/lib/x86_64-linux-gnu/libsndio.so*
```

For a project dependent only on OpenGL and SDL2 these are the basic libraries it needs.
